---
- name:  "install http"
  hosts:  all
  tasks:  
  - name: "install httpd package"
    yum:
     name:  httpd
     state:  present
  - name: "start httpd"
    service:
     name:  httpd
     state:  started
     


